### ISSUE TITLE
horizon: Something went wrong!  An unexpected error has occurred. Try refreshing the page. If that doesn't help, contact your local administrator.

### ISSUE THREAD

**Issue by AJNOURI** [AJNOURI/COA#17]
![selection_461](https://cloud.githubusercontent.com/assets/1716020/19098337/a7852a7a-8aac-11e6-9faa-12e4baf15887.png)

**Comment by AJNOURI** [comment]
was a direct consequence of recreating admin user  (https://github.com/AJNOURI/COA/issues/7)

**Comment by AJNOURI** [comment]
Solved the issue by recreating user, service and endpoints of non-working services.

### Glance
Recreated (delete/create) glance user, service and endpoints
`$ glance image-list`

> +--------------------------------------+--------------------------+-------------+------------------+----------+--------+
> | ID                                   | Name                     | Disk Format | Container Format | Size     | Status |
> +--------------------------------------+--------------------------+-------------+------------------+----------+--------+
> | 4c78f531-922d-49e0-b4e8-b0c5866b03a5 | cirros-0.3.4-x86_64-disk | qcow2       | bare             | 13287936 | active |
> +--------------------------------------+--------------------------+-------------+------------------+----------+--------+

### Nova
Recreated (delete/create) nova user, service and endpoints

`$ nova list`

> +--------------------------------------+------+---------+------------+-------------+-----------------------+
> | ID                                   | Name | Status  | Task State | Power State | Networks              |
> +--------------------------------------+------+---------+------------+-------------+-----------------------+
> | 43f47275-069f-4106-8257-b043e8d1af61 | i1   | SHUTOFF | -          | Shutdown    | demo-net=192.168.10.2 |
> +--------------------------------------+------+---------+------------+-------------+-----------------------+

`$ nova net-list`

> +--------------------------------------+----------+------+
> | ID                                   | Label    | CIDR |
> +--------------------------------------+----------+------+
> | a180d59c-aea6-4c6f-a08b-43a63cda0df2 | ext-net  | -    |
> | a6381606-8eed-4087-b4e9-0d085d35cd5c | demo-net | -    |
> +--------------------------------------+----------+------+

### Neutron
Recreated (delete/create) neutron user, service and endpoints

`$ neutron net-list`

> +--------------------------------------+----------+-------------------------------------------------------+
> | id                                   | name     | subnets                                               |
> +--------------------------------------+----------+-------------------------------------------------------+
> | a180d59c-aea6-4c6f-a08b-43a63cda0df2 | ext-net  | 42415b78-31e3-4094-97e0-3bde6c5c3ba4 192.168.100.0/24 |
> | a6381606-8eed-4087-b4e9-0d085d35cd5c | demo-net | a6826671-a572-4f27-ab33-635be9a1971e 192.168.10.0/24  |
> +--------------------------------------+----------+-------------------------------------------------------+

$ neutron subnet-list

> +--------------------------------------+-------------+------------------+--------------------------------------------------------+
> | id                                   | name        | cidr             | allocation_pools                                       |
> +--------------------------------------+-------------+------------------+--------------------------------------------------------+
> | 42415b78-31e3-4094-97e0-3bde6c5c3ba4 | ext-subnet  | 192.168.100.0/24 | {"start": "192.168.100.200", "end": "192.168.100.250"} |
> | a6826671-a572-4f27-ab33-635be9a1971e | demo-subnet | 192.168.10.0/24  | {"start": "192.168.10.2", "end": "192.168.10.254"}     |
> +--------------------------------------+-------------+------------------+--------------------------------------------------------+

### Horizon
And restarted Apache and memcached 
```
service apache2 restart
service memcached restart
```

![selection_462](https://cloud.githubusercontent.com/assets/1716020/19099122/a568bd22-8ab3-11e6-9a88-a66a9bcd2b88.png)

**Comment by keludong** [comment]
check the HOST_IP set  in /etc/memcached.conf is the correct HOST_IP, not '-l 127.0.0.1' or other incorrect value
