### ISSUE TITLE
heat: ERROR: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'controller' ([Errno -2] Name or service not known)")

### ISSUE THREAD

**Issue by AJNOURI** [AJNOURI/COA#52]
After heat parameter configuration (/etc/heat/heat.conf), I cannot populate heat database:

`su -s /bin/sh -c "heat-manage db_sync" heat`

> No handlers could be found for logger "heat.common.config"
> 2017-01-06 00:23:01.928 2984 WARNING heat.openstack.common.db.sqlalchemy.session [-] This application has not enabled MySQL traditional mode, which means silent data corruption may occur. Please encourage the application developers to enable this mode.
> 2017-01-06 00:23:01.931 2984 WARNING heat.openstack.common.db.sqlalchemy.session [-] SQL connection failed. 10 attempts left.
> 2017-01-06 00:23:11.940 2984 WARNING heat.openstack.common.db.sqlalchemy.session [-] SQL connection failed. 9 attempts left.
> 2017-01-06 00:23:21.948 2984 WARNING heat.openstack.common.db.sqlalchemy.session [-] SQL connection failed. 8 attempts left.
> 2017-01-06 00:23:31.954 2984 WARNING heat.openstack.common.db.sqlalchemy.session [-] SQL connection failed. 7 attempts left.
> 2017-01-06 00:23:41.966 2984 WARNING heat.openstack.common.db.sqlalchemy.session [-] SQL connection failed. 6 attempts left.
> 2017-01-06 00:23:51.976 2984 WARNING heat.openstack.common.db.sqlalchemy.session [-] SQL connection failed. 5 attempts left.
> 2017-01-06 00:24:01.988 2984 WARNING heat.openstack.common.db.sqlalchemy.session [-] SQL connection failed. 4 attempts left.
> 2017-01-06 00:24:11.993 2984 WARNING heat.openstack.common.db.sqlalchemy.session [-] SQL connection failed. 3 attempts left.
> 2017-01-06 00:24:22.005 2984 WARNING heat.openstack.common.db.sqlalchemy.session [-] SQL connection failed. 2 attempts left.
> 2017-01-06 00:24:32.017 2984 WARNING heat.openstack.common.db.sqlalchemy.session [-] SQL connection failed. 1 attempts left.
> ERROR: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'controller' ([Errno -2] Name or service not known)")
>

**Comment by AJNOURI** [comment]
in (/etc/heat/heat.conf I used "controller" which doesn't resolve to anything.
So added a resolution to /etc/hosts.

Now works fine

**Comment by Navya-S** [comment]
Hi @AJNOURI ,
The below command is prompting for password and throwing the authentication error with the password being given for "heat" user. tried with heat_domain_admin password too.
 su -s /bin/sh -c "heat-manage db_sync" heat
Could you please let me know which password should be entered for the above.
